name: HAMQTT Integration Workflow - Oxxio
env:
  INTEGRATION_NAME: Oxxio

on:
  push:
    branches: [ "main" ]
    tags: [ 'v*.*.*' ]
    paths:
      - HAMQTT.Integration.${{ env.INTEGRATION_NAME }}/**
  pull_request:
    branches: [ "main" ]
    paths:
      - HAMQTT.Integration.${{ env.INTEGRATION_NAME }}/**

jobs:
  build:
    uses: mavanmanen/HAMQTT/.github/workflows/hamqtt-integration-workflow.yml@main
    with:
      integration_name: ${{ env.INTEGRATION_NAME }}
